name: 'Generate changelog with git-chglog'
description: 'Generate a changelog using using the git-chlog tool'
branding:
  icon: 'code'  
  color: 'green'

inputs:
  next_version:
    description: 'Next version'
    required: true

  config_dir:
    description: 'git-chglog configuration directory'
    default: '.chglog'
    required: true

  filename:
    description: 'Filename to write the changelog to'
    default: 'CHANGELOG.md'
    required: false

  git_chglog_version:
    description: 'Version of git-chglog to run'
    default: 'v.0.15.0'
    required: false

  tag:
    description: 'Optional, Generate changelog only for this tag.'
    default: ''
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -c
    - ${{ inputs.config_dir }}
    - -n
    - ${{ inputs.next_version }}
    - -o
    - ${{ inputs.filename }}
    - -t
    - ${{ inputs.tag }}
    - -v
    - ${{ inputs.git_chglog_version }}
